[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

# Redirects for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle API routes (if you have any)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Dashboard redirect
[[redirects]]
  from = "/dashboard"
  to = "/dashboard/default"
  status = 302

# Handle authentication routes
[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

# Handle business routes
[[redirects]]
  from = "/business-pricing"
  to = "/business-pricing"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (will be set in Netlify dashboard)
# NEXT_PUBLIC_API_URL
# NEXT_PUBLIC_APP_URL
